"""
Django settings for Insight project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!n&penw%*h1t_^45l3km-a$e7ql!tg=%x6zkrgk-slo-*(k*2q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Insight.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Insightapp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Insight.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Insightapp/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)
SITE_ID = 1
LOGIN_REDIRECT_URL = 'home'

AUTH_USER_MODEL = 'Insightapp.CustomUser'

# Additional allauth settings

ACCOUNT_LOGOUT_REDIRECT_URL = '/home'  # Adjust to where to go after logout

# If you want email verification
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Can be 'mandatory', 'optional', or 'none'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',  # Custom toolbar
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],  # Basic text styles
            ['Blockquote'],  # Blockquote
            ['NumberedList', 'BulletedList'],  # Lists
            ['Link', 'Unlink'],  # Links
            ['Undo', 'Redo'],  # Undo/Redo
            ['RemoveFormat'],  # Clear formatting
            ['Maximize']  # Full-screen mode
        ],
        'height': 300,
        'width': 'auto',
        'autoGrow_minHeight': 300,
        'autoGrow_maxHeight': 600,
        'autoGrow_bottomSpace': 10,
        'removePlugins': 'resize',  # Disable resizing
        'extraPlugins': ','.join([
            'autogrow',  # Auto-growing editor
            'uploadimage',  # Image upload
            'pastefromword',  # Paste from Word
            'contenttemplates',  # Content Templates
            'a11ychecker',  # Accessibility Checker
        ]),
        'contentsCss': ['https://cdn.example.com/ckeditor/contents.css'],  # External CSS for styling
        'allowedContent': True,  # Allow all content
        'basicEntities': False,
        'entities_greek': False,
        'entities_latin': False,
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'forcePasteAsPlainText': True,  # Paste as plain text by default
        'removeDialogTabs': 'link:advanced;image:advanced',  # Simplify dialogs
        'image2_alignClasses': ['align-left', 'align-center', 'align-right'],
        'templates_files': ['/ckeditor/templates.js'],  # Custom template file
        'templates_replaceContent': False,
    },
}
